[mAppIcon1]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=1
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 1 ? 0 : 1 )

[mAppIcon2]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=2
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 2 ? 0 : 1 )

[mAppIcon3]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=3
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 3 ? 0 : 1 )

[mAppIcon4]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=4
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 4 ? 0 : 1 )

[mAppIcon5]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=5
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 5 ? 0 : 1 )

[mAppIcon6]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=6
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 6 ? 0 : 1 )

[mAppIcon7]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=7
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 7 ? 0 : 1 )

[mAppIcon8]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=8
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 8 ? 0 : 1 )

[mAppIcon9]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=9
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 9 ? 0 : 1 )

[mAppIcon10]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=10
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 10 ? 0 : 1 )

[mAppIcon11]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=11
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 11 ? 0 : 1 )

[mAppIcon12]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=12
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 12 ? 0 : 1 )

[mAppIcon13]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=13
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 13 ? 0 : 1 )

[mAppIcon14]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=14
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 14 ? 0 : 1 )

[mAppIcon15]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=15
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 15 ? 0 : 1 )

[mAppIcon16]
Measure=Plugin
Plugin=FileView
Path=[mApps]
Type=Icon
IconPath=#IconsPath#\#CURRENTSECTION#.ico
IconSize=[#gIconSize[#gIconSize]]
Index=16
DynamicVariables=1
UpdateDivider=1000
Disabled=( [mAppCount] >= 16 ? 0 : 1 )

